In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [3]:
df = pd.read_csv("nursery.data.txt")

In [9]:
df.head()

parents has_nurs      form children     housing     finance         social  \
0   usual   proper  complete        1  convenient  convenient        nonprob   
1   usual   proper  complete        1  convenient  convenient        nonprob   
2   usual   proper  complete        1  convenient  convenient        nonprob   
3   usual   proper  complete        1  convenient  convenient  slightly_prob   
4   usual   proper  complete        1  convenient  convenient  slightly_prob   

        health application  
0  recommended   recommend  
1     priority    priority  
2    not_recom   not_recom  
3  recommended   recommend  
4     priority    priority

In [10]:
from sklearn.cross_validation import train_test_split

c:\users\nikola\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [29]:
X = df.drop('application',axis=1)
X = X.apply(lambda x: pd.factorize(x)[0])
X.head()

parents  has_nurs  form  children  housing  finance  social  health
0        0         0     0         0        0        0       0       0
1        0         0     0         0        0        0       0       1
2        0         0     0         0        0        0       0       2
3        0         0     0         0        0        0       1       0
4        0         0     0         0        0        0       1       1

In [ ]:
y = df['application']

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7, random_state=101)

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
rfc = RandomForestClassifier(n_estimators=200)

In [23]:
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [24]:
rfc_pred = rfc.predict(X_test)

In [25]:
from sklearn.metrics import classification_report, confusion_matrix

In [27]:
print(classification_report(y_test, rfc_pred))

             precision    recall  f1-score   support

  not_recom       1.00      1.00      1.00      3081
   priority       0.96      0.98      0.97      2925
  recommend       0.00      0.00      0.00         1
 spec_prior       0.98      0.97      0.98      2838
 very_recom       0.99      0.83      0.91       227

avg / total       0.98      0.98      0.98      9072



c:\users\nikola\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [28]:
print(confusion_matrix(y_test, rfc_pred))

[[3081    0    0    0    0]
 [   0 2867    0   58    0]
 [   0    0    0    0    1]
 [   0   76    0 2762    0]
 [   0   38    0    0  189]]
