In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
df = pd.read_csv("nursery.data.txt")

In [3]:
df.head()

parents has_nurs      form children     housing     finance         social  \
0   usual   proper  complete        1  convenient  convenient        nonprob   
1   usual   proper  complete        1  convenient  convenient        nonprob   
2   usual   proper  complete        1  convenient  convenient        nonprob   
3   usual   proper  complete        1  convenient  convenient  slightly_prob   
4   usual   proper  complete        1  convenient  convenient  slightly_prob   

        health application  
0  recommended   recommend  
1     priority    priority  
2    not_recom   not_recom  
3  recommended   recommend  
4     priority    priority

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12960 entries, 0 to 12959
Data columns (total 9 columns):
parents        12960 non-null object
has_nurs       12960 non-null object
form           12960 non-null object
children       12960 non-null object
housing        12960 non-null object
finance        12960 non-null object
social         12960 non-null object
health         12960 non-null object
application    12960 non-null object
dtypes: object(9)
memory usage: 455.7+ KB


In [9]:
from sklearn.cross_validation import train_test_split

c:\users\nikola\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [20]:
X = df.drop('application',axis=1)
X = X.apply(lambda x: pd.factorize(x)[0])
y = df['application']

In [32]:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7, random_state=42)

In [33]:
from sklearn.naive_bayes import GaussianNB

In [34]:
gnb = GaussianNB()

In [35]:
gnb.fit(X_train, y_train)

GaussianNB(priors=None)

In [36]:
gnb_pred = gnb.predict(X_test)

In [37]:
from sklearn.metrics import classification_report, confusion_matrix

In [38]:
print(classification_report(y_test, gnb_pred))

             precision    recall  f1-score   support

  not_recom       1.00      1.00      1.00      3023
   priority       0.84      0.43      0.57      3019
  recommend       0.00      0.00      0.00         2
 spec_prior       0.93      0.82      0.87      2788
 very_recom       0.12      1.00      0.21       240

avg / total       0.90      0.75      0.80      9072



c:\users\nikola\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [39]:
print(confusion_matrix(y_test, gnb_pred))

[[3023    0    0    0    0]
 [   0 1299    0  173 1547]
 [   0    0    0    0    2]
 [   0  246    0 2279  263]
 [   0    0    0    0  240]]
